# .sqa/config.yml - jenkins-pipeline-library configuration file

environment:
  JPL_DOCKERFORCEBUILD: "True"
  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      thermal-bridges-rooftops-detector:
        container: thisrepo-testing
        commands:
        - sh -c 'git config --global --add safe.directory $PWD/TBBRDet'
        - sh -c 'git submodule update --init --remote --recursive'
        - sh -c "./sqa-init.sh && flake8 --format=pylint tbbrdet_api"

  qc_coverage:
    repos:
      thermal-bridges-rooftops-detector:
        container: thisrepo-testing
        commands:
        - sh -c 'git config --global --add safe.directory $PWD/TBBRDet'
        - sh -c 'git submodule update --init --remote --recursive'
        - sh -c "pytest --cov=tbbrdet_api --cov-report=html:./htmlcov tbbrdet_api/tests"

  qc_security:
    repos:
      thermal-bridges-rooftops-detector:
        container: thisrepo-testing
        commands:
        - sh -c 'git config --global --add safe.directory $PWD/TBBRDet'
        - sh -c 'git submodule update --init --remote --recursive'
        - sh -c "bandit -c bandit.yaml -r tbbrdet_api -x tests"

timeout: 1200
