# .sqa/config.yml - jenkins-pipeline-library configuration file

# generic configuration: workspace, agents
config:
  credentials:
    - id: indigobot
      username_var: JPL_DOCKERUSER
      password_var: JPL_DOCKERPASS

environment:
  JPL_DOCKERPUSH: "deephdc/uc-emvollmer-deep-oc-tbbrdet_api:cpu-test"
  JPL_DOCKERFORCEBUILD: "True"
  LANG: C.UTF-8

sqa_criteria:
  QC.Sty:
    repos:
      tbbrdet_api:
        container: tbbrdet_api-testing
        commands:
        - sh -c "./sqa-init.sh && flake8 --format=pylint tbbrdet_api"

  QC.Cov:
    repos:
      tbbrdet_api:
        container: tbbrdet_api-testing
        commands:
        - sh -c "pytest --cov=tbbrdet_api --cov-report=html:./htmlcov tbbrdet_api/tests"

  QC.Sec:
    repos:
      tbbrdet_api:
        container: tbbrdet_api-testing
        commands:
        - sh -c "bandit -r tbbrdet_api -x tests"

timeout: 1200
