services:
  tbbrdet-testing:
    image: deephdc/uc-emvollmer-deep-oc-tbbrdet_api:base
    working_dir: /srv
    volumes:
      - type: bind
        source: ./
        target: /srv
    command: sleep infinity

  uc-emvollmer-deep-oc-tbbrdet_api-cpu
     build:
        context: "."
        dockerfile: "./docker/Dockerfile"
        args:
          tag: "base"
          branch: ${GIT_BRANCH}
     image: "deephdc/uc-emvollmer-deep-oc-tbbrdet_api:${CPU_TAG}"

  uc-emvollmer-deep-oc-tbbrdet_api-gpu
     build:
        context: "."
        dockerfile: "./docker/Dockerfile"
        args:
          tag: "base"
          branch: ${GIT_BRANCH}
     image: "deephdc/uc-emvollmer-deep-oc-tbbrdet_api:${GPU_TAG}"