version: "3.7"

services:
  tbbrdet_api-testing:
    image: vykozlov/uc-emvollmer-deep-oc-tbbrdet_api:base
    working_dir: /srv
    volumes:
      - type: bind
        source: ./
        target: /srv
    command: sleep infinity

  tbbrdet_api-cpu:
    build:
      context: "."
      dockerfile: "./docker/Dockerfile"
      args:
        tag: "base"
        branch: "test"
    image: "deephdc/uc-emvollmer-deep-oc-tbbrdet_api:cpu"

  tbbrdet_api-gpu:
    build:
      context: "."
      dockerfile: "./docker/Dockerfile"
      args:
        tag: "base"
        branch: ${GIT_BRANCH}
    image: "deephdc/uc-emvollmer-deep-oc-tbbrdet_api:${GPU_TAG}"
