version: "3.7"

services:
  thisrepo-testing:
    image: "ai4oshub/thermal-bridges-rooftops-detector:cicd"
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv
    command: >
      sh -c "git config --global --add safe.directory /srv &&
             tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /srv
